name: Local functional tests
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

env:
  BASE_BRANCH: ${{ github.base_ref || (endsWith(github.ref, '_feature') && 'feature' || 'main') }}

jobs:
  sanitizer-ub-address:
    name: Running Sanitizer tests (UB + Address)
    runs-on: ubuntu-latest
    env:
      GEN: ninja
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      MINIMAL_TEST_DEPENDENCIES: 1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: a1a1cbc975abf909a6c8985a6a2b8fe20bbd9bd6

      - uses: rui314/setup-mold@v1

      - name: Configure OpenSSL for Rust
        run: |
          echo "OPENSSL_ROOT_DIR=`pwd`/build/debug/vcpkg_installed/x64-linux" >> $GITHUB_ENV
          echo "OPENSSL_DIR=`pwd`/build/debug/vcpkg_installed/x64-linux" >> $GITHUB_ENV
          echo "OPENSSL_USE_STATIC_LIBS=true" >> $GITHUB_ENV

      - name: Build
        shell: bash
        env:
          CUSTOM_LINKER: mold
        run: |
          make generate-data
          make debug

      - name: Test
        shell: bash
        run: |
          GENERATED_DATA_AVAILABLE=1 make test_debug

      - name: Print Rust logs
        if: always()
        run: |
          for filename in build/debug/rust/src/*/*build-*.log; do 
            echo Printing logs for file $filename
            cat $filename;
            echo Done printing logs for $filename
          done

  sanitizer-thread:
    name: Running Sanitizer tests (Thread)
    runs-on: ubuntu-latest
    env:
      GEN: ninja
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      MINIMAL_TEST_DEPENDENCIES: 1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build

      - uses: rui314/setup-mold@v1

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: a1a1cbc975abf909a6c8985a6a2b8fe20bbd9bd6

      - name: Configure OpenSSL for Rust
        run: |
          echo "OPENSSL_ROOT_DIR=`pwd`/build/debug/vcpkg_installed/x64-linux" >> $GITHUB_ENV
          echo "OPENSSL_DIR=`pwd`/build/debug/vcpkg_installed/x64-linux" >> $GITHUB_ENV
          echo "OPENSSL_USE_STATIC_LIBS=true" >> $GITHUB_ENV

      - name: Build
        shell: bash
        env:
          SANITIZER_MODE: thread
          CUSTOM_LINKER: mold
        run: |
          make generate-data
          df -h
          du -h -d 1 .
          rm -rf venv
          make debug

      - name: Test
        shell: bash
        run: |
          GENERATED_DATA_AVAILABLE=1 make test_debug

      - name: Print Rust logs
        if: always()
        run: |
          for filename in build/debug/rust/src/*/*build-*.log; do 
            echo Printing logs for file $filename
            cat $filename;
            echo Done printing logs for $filename
          done